riotrecords/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("login_user/", views.login_user, name="login"),
    path("logout_user/", views.logout_user, name="logout"),
    path("register_user/", views.register_user, name="register"),
    path('profile/', views.profile, name='profile'),
]

riotrecords/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:item_id>/', views.add_to_cart, name='add_to_cart'),
    path('delete/<int:cartitem_id>/', views.delete_from_cart, name='delete_from_cart'),
    path('order/', views.order, name='order'),
]

riotrecords/riotrecords/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("catalog.urls")),
    path('accounts/', include("accounts.urls")),
    path('cart/', include("cart.urls")),
    path('stats/', include("stats.urls")),
]

handler404 = 'riotrecords.views.handle_404_error'

riotrecords/catalog/models.py
from django.db import models
from django.contrib.auth.models import User


class Item(models.Model):
    album_name = models.CharField(max_length=150)
    band_name = models.CharField(max_length=150)
    price = models.IntegerField()
    year = models.IntegerField()
    image = models.CharField(max_length=300)

    def __str__(self):
        return f"{self.album_name} - {self.band_name}"


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ORDER_STATUS = {
        "PD": "pending",
        "PR": "processing",
        "SH": "shipped",
        "DE": "delivered",
    }
    status = models.CharField(max_length=30, choices=ORDER_STATUS, default="PD")
    address = models.CharField(max_length=200)
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Order {self.id} (user={self.user})"


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="+")

riotrecords/accounts/views.py
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect
from catalog.models import Order
from django.contrib.auth.decorators import login_required

def login_user(request):

    error_msg = ""

    if request.method == "GET" and request.GET.get("next") == "/stats/":
        error_msg = "Данная секция доступна только администратора"

    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            if user.is_staff:
                return redirect("/admin")
            else:
                return redirect("catalog:index")
        else:
            error_msg = f"Пользователя \"{username}\" с данным паролем не существует. Попробуйте ещё раз."

    return render(request, "accounts/login.html", context={
        "error_msg": error_msg
    })


def logout_user(request):
    logout(request)
    return redirect("catalog:index")


def register_user(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        password = request.POST["password"]

        if not User.objects.filter(username=username).exists():
            User.objects.create_user(
                username=username,
                email=email,
                password=password
            )
            return redirect("catalog:index")
        else:
            return render(request, "accounts/registration.html", context={
                "error_msg": f"Ошибка регистрации. Пользователь с таким \"{username}\" уже существует."
            })

    return render(request, "accounts/registration.html")



@login_required(login_url="accounts:login")
def profile(request):
    orders = Order.objects.filter(user=request.user)
    return render(request, "accounts/profile.html", {'orders': orders})

riotrecords/accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Вход</title>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card mt-5">
                    <div class="card-body">
                        <h2 class="card-title text-center">Вход</h2>
                        {% if error_msg %}
                            <div class="alert alert-warning" role="alert">
                              {{ error_msg }}
                            </div>
                        {% endif %}
                        <form method="post" action="{% url 'accounts:login' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <input name="username" class="form-control" placeholder="Имя пользователя">
                            </div>
                            <div class="form-group">
                                <input type="password" name="password" class="form-control" placeholder="Пароль">
                            </div>
                            <button type="submit" class="btn btn-primary btn-block">Войти</button>
                        </form>

                        <div>
                            Нет аккаунта? <a href="{% url 'accounts:register' %}">Зарегестрироваться</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

riotrecords/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}Профиль{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1>Ваш профиль</h1>
    <h2>Ваши заказы</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID заказа</th>
                <th>Статус</th>
                <th>Адрес</th>
                <th>Дата</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
                <tr>
                    <td>{{ order.id }}</td>
                    <td>{{ order.get_status_display }}</td>
                    <td>{{ order.address }}</td>
                    <td>{{ order.time }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

riotrecords/accounts/templates/accounts/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Регистрация</title>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card mt-5">
                    <div class="card-body">
                        <h2 class="card-title text-center">Регистрация</h2>

                        {% if error_msg %}
                            <div class="alert alert-warning" role="alert">
                              {{ error_msg }}
                            </div>
                        {% endif %}

                        <form method="post" action="{% url 'accounts:register' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <input name="username" class="form-control" placeholder="Имя пользователя">
                            </div>
                            <div class="form-group">
                                <input type="email" name="email" class="form-control" placeholder="Email">
                            </div>
                            <div class="form-group">
                                <input type="password" name="password" class="form-control" placeholder="Пароль">
                            </div>
                            <button type="submit" class="btn btn-primary btn-block">Зарегестрироваться</button>
                        </form>
                        <div>
                            Уже есть аккаунт? <a href="{% url 'accounts:login' %}">Войти</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>