riotrecords/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("login_user/", views.login_user, name="login"),
    path("logout_user/", views.logout_user, name="logout"),
    path("register_user/", views.register_user, name="register"),
    path('profile/', views.profile, name='profile'),
]

riotrecords/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:item_id>/', views.add_to_cart, name='add_to_cart'),
    path('delete/<int:cartitem_id>/', views.delete_from_cart, name='delete_from_cart'),
    path('order/', views.order, name='order'),
]

riotrecords/catalog/urls.py
from django.urls import path
from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.index, name='index'),
]

riotrecords/riotrecords/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("catalog.urls")),
    path('accounts/', include("accounts.urls")),
    path('cart/', include("cart.urls")),
    path('stats/', include("stats.urls")),
]

handler404 = 'riotrecords.views.handle_404_error'

riotrecords/catalog/models.py
from django.db import models
from django.contrib.auth.models import User


class Item(models.Model):
    album_name = models.CharField(max_length=150)
    band_name = models.CharField(max_length=150)
    price = models.IntegerField()
    year = models.IntegerField()
    image = models.CharField(max_length=300)

    def __str__(self):
        return f"{self.album_name} - {self.band_name}"


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ORDER_STATUS = {
        "PD": "pending",
        "PR": "processing",
        "SH": "shipped",
        "DE": "delivered",
    }
    status = models.CharField(max_length=30, choices=ORDER_STATUS, default="PD")
    address = models.CharField(max_length=200)
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Order {self.id} (user={self.user})"


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="+")

riotrecords/catalog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Item

def index(request):
    return render(request, "catalog/index.html", context={"Items": Item.objects.all()})

riotrecords/catalog/templates/catalog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Riot Records{% endblock title %}</title>

    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

    <!-- Navbar -->
    {% block navbar %} {% include "catalog/navbar.html" %} {% endblock navbar %}

    <!-- Main Content -->
    {% block content %}{% endblock content %}

    <!-- Footer -->
    <footer class="bg-dark text-white mt-5 p-4 text-center">
        <p>© 2024 RiotRecords</p>
    </footer>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

riotrecords/catalog/templates/catalog/index.html
{% extends "catalog/base.html" %}

{% block content %}

<div class="container mt-5">
    <div class="row">
        <div class="col text-center">
            {% if user.is_authenticated %}
                <h1>Здравствуйте, {{ user.get_username }}!</h1>
            {% else %}
                <h1>Добро пожаловать в RiotRecords!</h1>
            {% endif %}
            <p>Здесь вы найдете лучшие виниловые пластинки.</p>
        </div>
    </div>
    <div class="row mt-4">
        {% for item in Items %}
        <!-- Album card -->
        <div class="col-md-4">
            <div class="card mb-4">
                <img src="{{ item.image }}" class="card-img-top">
                <div class="card-body" id="{{ item.id }}">
                    <h5 class="card-title">{{ item.album_name }}</h5>
                    <p class="card-text">Исполнитель: {{ item.band_name }}</p>
                    <p class="card-text">Год выпуска: {{ item.year }}</p>
                    <p class="card-text">Цена: {{ item.price }} $</p>
                    <a class="btn btn-primary add-to-cart" href="{% url 'cart:add_to_cart' item.id %}">Добавить в корзину</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

riotrecords/catalog/templates/catalog/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'catalog:index' %}">RiotRecords</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <li class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'cart:cart_detail' %}" id="cart">
                    Корзина
                </a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:profile' %}">Профиль</a>
                </li>
                <li class="nav-item">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">
                        Выйти
                    </a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">
                        Войти
                    </a>
                </li>
            {% endif %}
        </ul>
    </li>
</nav>