riotrecords/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:item_id>/', views.add_to_cart, name='add_to_cart'),
    path('delete/<int:cartitem_id>/', views.delete_from_cart, name='delete_from_cart'),
    path('order/', views.order, name='order'),
]

riotrecords/catalog/urls.py
from django.urls import path
from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.index, name='index'),
]

riotrecords/riotrecords/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("catalog.urls")),
    path('accounts/', include("accounts.urls")),
    path('cart/', include("cart.urls")),
    path('stats/', include("stats.urls")),
]

handler404 = 'riotrecords.views.handle_404_error'

riotrecords/cart/models.py
from django.db import models
from catalog.models import Item
from django.contrib.auth.models import User


class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    added_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"CartItem(id={self.id}, user={self.user}, item={self.item})"

riotrecords/cart/forms.py
from django import forms


class OrderForm(forms.Form):
    address = forms.CharField()

riotrecords/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import CartItem
from catalog.models import Item, Order, OrderItem
from django.contrib.auth.decorators import login_required
from .forms import OrderForm
from .models import CartItem


@login_required(login_url="accounts:login")
def cart_detail(request):
    cart_items = CartItem.objects.filter(user=request.user)
    return render(request, 'cart/cart_detail.html', {'cart_items': cart_items})


@login_required(login_url="accounts:login")
def add_to_cart(request, item_id):
    item = get_object_or_404(Item, id=item_id)
    user = request.user

    cart_item = CartItem.objects.create(user=user, item=item)
    cart_item.save()

    return redirect("catalog:index")


@login_required(login_url="accounts:login")
def delete_from_cart(request, cartitem_id):
    user = request.user
    cart_item = get_object_or_404(CartItem, id=cartitem_id, user=user)
    cart_item.delete()

    return redirect("cart:cart_detail")


@login_required(login_url="accounts:login")
def order(request):
    if request.method == "POST":
        user = request.user
        address = request.POST["address"]

        # Get user cart items
        cart_items = CartItem.objects.filter(user=user)

        if len(cart_items) < 1:
            return render(request, 'cart/order.html', {'error_msg': "У вас пустая корзина"})

        # Create order
        order = Order.objects.create(user=user, address=address)
        order.save()

        # Create order items
        for cart_item in cart_items:
            order_item = OrderItem.objects.create(order=order, item=cart_item.item)
            order_item.save()

        # Clear cart for current user
        cart_items.delete()

        return render(request, 'cart/success_order.html')

    form = OrderForm()
    return render(request, 'cart/order.html', {'form': form})

riotrecords/cart/templates/cart/cart_detail.html
{% extends 'base.html' %}

{% block title %}Корзина{% endblock title %}

{% block content %}
<div class="container mt-5">
    <h1>Ваша корзина</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Название альбома</th>
                <th>Исполнитель</th>
                <th>Цена</th>
            </tr>
        </thead>
        <tbody>
            {% for cart_item in cart_items %}
                <tr>
                    <td>{{ cart_item.item.album_name }}</td>
                    <td>{{ cart_item.item.band_name }}</td>
                    <td>{{ cart_item.item.price }} руб.</td>
                    <td><a href="{% url 'cart:delete_from_cart' cart_item.id %}" class="btn btn-danger">Удалить</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'catalog:index' %}" class="btn btn-secondary">Продолжить покупки</a>
    <a href="{% url 'cart:order' %}" class="btn btn-primary {% if cart_items|length < 1 %} disabled {% endif %}">Оформить заказ</a>
</div>
{% endblock content %}

riotrecords/cart/templates/cart/order.html
{% extends 'base.html' %}

{% block title %}Оформление заказа{% endblock title %}

{% block content %}
<div class="container mt-5">
    <h1>Оформление заказа</h1>

    {% if error_msg %}
        <div class="alert alert-warning" role="alert">
            {{ error_msg }}
        </div>
    {% endif%}

    <form action="{% url 'cart:order' %}" method="post">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <input class="btn btn-primary" type="submit" value="Оформить заказ">
        <a href="{% url 'cart:cart_detail' %}" class="btn btn-secondary">Вернуться в корзину</a>
    </form>
</div>
{% endblock content %}

riotrecords/cart/templates/cart/success_order.html
{% extends 'base.html' %}

{% block title %}Оформление заказа{% endblock title %}

{% block content %}
<div class="container mt-5">
    <h1>Заказ успешно оформлен!</h1>
    <a href="{% url 'catalog:index' %}" class="btn btn-dark">Вернуться в магазин</a>
</div>
{% endblock content %}