riotrecords/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:item_id>/', views.add_to_cart, name='add_to_cart'),
    path('delete/<int:cartitem_id>/', views.delete_from_cart, name='delete_from_cart'),
    path('order/', views.order, name='order'),
]

riotrecords/riotrecords/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("catalog.urls")),
    path('accounts/', include("accounts.urls")),
    path('cart/', include("cart.urls")),
    path('stats/', include("stats.urls")),
]

handler404 = 'riotrecords.views.handle_404_error'

riotrecords/stats/urls.py
from django.urls import path

from . import views

app_name = "stats"
urlpatterns = [
    path("", views.get_total_sales, name="get_total_sales"),
]

riotrecords/stats/models.py
from django.db import models

# Create your models here.

riotrecords/stats/forms.py
from django import forms
import catalog.models

class ChartForm(forms.Form):
    # CHOICES = <item_id, item_name>
    CHOICES = [(0, "-- Выберите товар --")]

    items = catalog.models.Item.objects.all().order_by("id")
    for item in items:
        CHOICES.append((item.id, str(item)))

    item_field = forms.ChoiceField(label="Выберите товар", choices=CHOICES, initial=CHOICES[0])

riotrecords/stats/views.py
from django.db import connection
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import render, redirect
import catalog.models
from .forms import ChartForm


def get_sales_info(item_id=0):
    labels = []
    data = []
    item_name = None

    if item_id != 0:
        item_name = str(catalog.models.Item.objects.get(id=item_id))

        with connection.cursor() as cursor:
            cursor.execute(
                f"SELECT TO_CHAR(DATE_TRUNC('day', catalog_order.time), 'DD/MM/YYYY') d, COUNT(catalog_orderitem.item_id) sales_count \
                FROM catalog_orderitem JOIN catalog_order ON catalog_orderitem.order_id = catalog_order.id \
                WHERE item_id = {item_id} \
                GROUP BY catalog_orderitem.item_id, d \
                ORDER BY d \
                "
            )
            rows = cursor.fetchall()

        for row in rows:
            date = row[0]
            sales_count = row[1]
            labels.append(date)
            data.append(sales_count)

    else:
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT TO_CHAR(DATE_TRUNC('day', catalog_order.time), 'DD/MM/YYYY') d, COUNT(catalog_orderitem.item_id) sales_count \
                FROM catalog_orderitem JOIN catalog_order ON catalog_orderitem.order_id = catalog_order.id \
                GROUP BY d \
                ORDER BY d"
            )
            rows = cursor.fetchall()

        for row in rows:
            date = row[0]
            sales_count = row[1]
            labels.append(date)
            data.append(sales_count)

    return labels, data, item_name


@staff_member_required(login_url="accounts:login", redirect_field_name='next')
def get_total_sales(request):
    labels = []
    data = []
    item_name = None
    form = ChartForm

    if request.method == "GET":
        labels, data, _ = get_sales_info()

    if request.method == "POST":
        form = ChartForm(request.POST)
        item_id = int(request.POST["item_field"])

        labels, data, item_name = get_sales_info(item_id)

    return render(request, "stats/charts.html", context={
        "labels": labels,
        "data": data,
        "item_name": item_name,
        "form": form
    })

riotrecords/stats/templates/stats/charts.html
{% extends "admin/base_site.html" %}

{% block content %}
<!-- Bootstrap -->
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
<!-- END Bootstrap -->

<!-- Chart -->
<div class="d-flex justify-content-center align-items-center">
  <canvas id="myChart" width="800" height="300"></canvas>
</div>
<!-- END Chart -->

<!-- Form -->
<div class="d-flex justify-content-center align-items-center">
  <form action="{% url 'stats:get_total_sales' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Отрисовать чарт продаж">
  </form>
</div>
<!-- END Form -->


<!-- Chart Scripts -->
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
  const ctx = document.getElementById('myChart');

  new Chart(ctx, {
    type: 'bar',
    data: {
      labels: [{% for label in labels %} "{{label}}", {% endfor %}],
      datasets: [{
        label: 'Total number of sales{% if item_name is not None %} {{ item_name }} {% endif %}',
        data: [{% for sale_count in data %} {{ sale_count }}, {% endfor %}],
        borderWidth: 1
      }]
    },
    options: {
      responsive: false,
      scales: {
        y: {
          beginAtZero: true
        }
      }
    }
  });
</script>
<!-- END Chart Scripts -->


<!-- Bootstrap -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<!-- END Bootstrap -->

{% endblock %}